name: CI - Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./Front

      - name: Run Lint
        run: npm run lint
        working-directory: ./Front

      - name: Build project
        run: npm run build
        working-directory: ./Front

      - name: Check build output
        run: ls -la ./Front/dist